# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc4f12cd5f47f78b490e5cf1606bef215e9aadd8f6d173cf8894ebad41c6d6426d9044ffa066ad8a3d37337f68a3245db58f9ba0c2c824c6e97980307fa7ac24

test:
  secret_key_base: ad698c547b083983592caaa7b0849c6a9356a2f78b3b4f9d3c1d6ea6c0254942c65b81dc97dd01d4cf4182cee8b8081c99ed1ffdf11eb21324112045de9a9930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
